# Generated by Django 2.2.4 on 2019-08-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mid', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('active_template', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='des', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('Inprod', models.ManyToManyField(related_name='Inprod', to='Storage.Product')),
                ('OutProd', models.ManyToManyField(related_name='Outprod', to='Storage.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(max_length=1000)),
                ('product', models.ManyToManyField(to='Storage.Product')),
            ],
        ),
    ]
